a = 'OneTwoThreeFourFiveSixSevenEightNineTenElevenTwelveThirteenFourteenFifteenSixteenSeventeenEighteenNineteenTwentyTwentyoneTwentytwoTwentyThreeTwentyFourTwentyFiveTwentySixTwentySevenTwentyEightTwentyNineThirtyThirtyOneThirtyTwoThirtyThreeThirtyFourThirtyFiveThirtySixThirtySevenThirtyEightThirtyNineFortyFortyOneFortyTwoFortyThreeFortyFourFortyFiveFortySixFortySevenFortyEightFortyNineFiftyFiftyOneFiftyTwoFiftyThreeFiftyFourFiftyFiveFiftySixFiftySevenFiftyEightFiftyNineSixtySixtyOneSixtyTwoSixtyThreeSixtyFourSixtyFiveSixtySixSixtySevenSixtyEightSixtyNineSeventySeventyOneSeventyTwoSeventyThreeSeventyFourSeventyFiveSeventySixSeventySevenSeventyEightSeventyNineEightyEightyOneEightyTwoEightyThreeEightyFourEightyFiveEightySixEightySevenEightyEightEightyNineNinetyNinetyOneNinetyTwoNinetyThreeNinetyFourNinetyFiveNinetySixNinetySevenNinetyEightNinetyNine'
b = 'OnehundredTwohundredThreehundredFourhundredFivehundredSixhundredSevenhundredEighthundredNinehundred'
c = 'Onethousand'


print len(a) * 10 + len(b) + len(c) + ((len(b)+27)*99)


